---
  - name: Initializing OS && farmware packages update
    hosts: centos8group
    gather_facts: no

    tasks:
      - name: Upgrade all packages
        ansible.builtin.dnf:
          name: "*"
          state: latest
